# Generated by Django 3.2.1 on 2021-09-06 00:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('email', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=8192, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=144)),
                ('title', models.CharField(max_length=144)),
                ('start_year', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('end_year', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Skill', max_length=1024)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('shortdescription', models.CharField(max_length=1024, null=True)),
                ('description', models.CharField(max_length=8192, null=True)),
                ('URL', models.CharField(max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blogimages', models.ManyToManyField(to='myportfolio.BlogImage')),
            ],
        ),
        migrations.CreateModel(
            name='CSTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('is_front_end', models.BooleanField(default=False, null=True)),
                ('Projects', models.ManyToManyField(to='myportfolio.Project')),
            ],
        ),
    ]
