# Generated by Django 3.2.1 on 2021-09-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workskill',
            name='job',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='WorkSkill',
        ),
    ]
